sudo: required
services:
  - docker

before_install:
  - docker build -t reeced/docker-reactor -f Dockerfile.dev .

script:
  - docker run -e CI=true reeced/docker-reactor npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-reactor"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-650031272273"
  bucket_path: "docker-reactor"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY